### PR TITLE
use s3 hook

### PR DESCRIPTION
**Pull request by Casyfill**
addresses #8 
Creates a local, dispensable `boto3.DEFAULT_SESSION` (boto3's singleton)  that GE will utilize. Once the job is done, the default session is removed.

This way you can assume the role or use your existing s3 hooks.
A few notes on implementation:

1. It slightly bugs me that this is aws-specific, ideally would be nice to create context/some essence that will take care of any connection passing, but I am not sure how to implement that at the moment
2.`botocontext.py` imports boto3 by default, I think airflow has boto3 as a dependency, but we definitely can move import into the class itself
3. The way it set up now, the operator requires S3Hook to be passed, therefore - to be initialized before. This is done purely as different airflow versions store S3Hook in different places, so it is easier to maintain it. In our internal plugin, we do pass connection id instead (and initialize s3Hook within the Context class).

### CODE REVIEW

**Review by spbail — COMMENTED** [review]
Thanks for submitting this PR! I'm a bit torn here regarding making this S3 specific in the base class, as you said in your comment. If the session would work the same way for other cloud storage providers, I'd be okay naming the param "session_hook" or something similar and allowing future implementations of SessionContext.

Otherwise I'd lean towards a subclass... What do you think?

**Comment by Casyfill** [comment]
I’d go with the first option, if possible. What other providers does GE
support or plans to support in the future?

**Comment by spbail** [comment]
@Casyfill I think my main concern is that GE basically supports any kind of backend as a datasource, and several cloud storage providers as stores for expectations and validation results, see https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_datasources.html and https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_metadata_stores.html. I don't know Airflow hooks well enough to know whether it would be possible to implement a SessionContext for other hooks (e.g. a bigquery connection) and then just use the context in the way you did? And I also don't know whether that would work for GE. 

I think we agree that an s3hook in the base class isn't ideal, so I'd love to see if this would work in the same way for another connection, e.g a BigQuery datasource or a GCS store instead of S3. I have yet to update the examples in this repo, but the astro-ge test repo has some implementations of using an S3 backend for expectation and validation stores: https://github.com/superconductive/astro-ge/blob/main/dags/example_great_expectations_dag.py

Happy to chat in Slack if you have any questions!

**Comment by Casyfill** [comment]
Totally! Let me try to abstract the hook at least in the naming. I never worked with BQ, let alone via Airflow, so can't say anything about that. So let me rename params so that _theoretically_ another connection can be used (say, via something like, and we can discuss specifics of BQ connection.

**Comment by Casyfill** [comment]
Hey @spbail , just got a chance to have another stab at this. Two thoughts here
1) as you can see, it is a bit hairy (takes another class to abstract away specifics)
2) I probably forgot to mention that, but for our flow, s3 access is required for documentation export, as well. So potentially we'd need both s3 connection for documents and some other connection (e.g. BigQuery, Snowflake) for the data pull. In your opinion, how shall we tackle that?

**Comment by spbail** [comment]
Re 1: I think this is ok, basically what I expected.
Re: 2: That's a good point, and we basically have any possible combination of backends we'd want to handle. You'd basically want to pass in multiple hooks and then have all GE operations happening in a context that has all those connections handled? I'd be curious if there are examples where someone's done this...?

**Comment by spbail** [comment]
We've had some discussions in the Slack channel and I think the best solution for this would be to implement a subclass of the base operator similar to the GreatExpectationsBigQueryOperator with the respective hooks you need, see example below from a user. 

```
def create_data_context_config(self):
        # Fetch the Airflow connection object
        connection_object = BaseHook.get_connection(self.aws_conn_id)
        extra_config = connection_object.extra_dejson
        AWS_ACCESS_KEY_ID=extra_config["aws_access_key_id"]
        AWS_SECRET_ACCESS_KEY=extra_config["aws_secret_access_key"]
        athena_url=f"awsathena+rest://{AWS_ACCESS_KEY_ID}:{AWS_SECRET_ACCESS_KEY}"\
            f"@athena.us-east-1.amazonaws.com/ge_tmp?s3_staging_dir=s3://{self.s3_bucket}/athena/query_output_tmp/"
        # Create GE data context config
        data_context_config = DataContextConfig(
            config_version=2,
            datasources={
                "athena_us_east_1": {
                    "data_asset_type": {
                        "class_name": "SqlAlchemyDataset",
                        "module_name": "great_expectations.dataset",
                    },
                    "class_name": "SqlAlchemyDatasource",
                    "module_name": "great_expectations.datasource",
                    "credentials": {
                        "url": athena_url,
                    },
                },
            },
            stores={
                "expectations_s3_store": {
                    "class_name": "ExpectationsStore",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "s3_bucket": self.s3_bucket,
                        "prefix": "great_expectations/expectations/",
                        "boto3_options": extra_config,
                    },
                },
                "validations_s3_store": {
                    "class_name": "ValidationsStore",
                    "store_backend": {
                        "class_name": "TupleS3StoreBackend",
                        "s3_bucket": self.s3_bucket,
                        "prefix": "great_expectations/uncommitted/validations/",
                        "boto3_options": extra_config,
                    },
                },
                "evaluation_parameter_store": {"class_name": "EvaluationParameterStore"},
            },
...
...
...
```

**Comment by spbail** [comment]
@Casyfill Just wanted to confirm since we've had a few conversations in Slack - I believe the solution would be to subclass the operator for specific hooks. I'll close this PR if that sounds ok to you.

**Pull request closed without merging**
