### PR TITLE
Add option to automatically generate data docs

### PR DESCRIPTION
**Pull request by juliankeppel**
We're using the GE Airflow operator for triggering automated data validations. We wanted to go one step further and automatically generate and publish the corresponding data docs. 

So I added this option. It will generate the data docs HTML structure at the local path on the Airflow instance (great_expectations/data_docs). This data docs can then be published for example by [pushing them to S3](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_s3.html).

Please note: I opened a PR first with a wrong email adress, so I closed it and re-opened it here.

### CODE REVIEW

**Comment by spbail** [comment]
Thanks for the contribution @juliankeppel and apologies for the late response! Here are two thoughts for this:
- If you're using Great Expectations version 0.13.7 and below, the "build data docs" action should be handled via the validation_operator parameter. With a default "great_expectations init" run your config should have a section for validation_operators that contains an action_list_operator in great_expectations.yml, which includes the build data docs action. Have you looked into this/did that not work for you?
- If you're using GE 0.13.8 and above, we dropped the validation_operator, but the LegacyCheckpoint runs through the default action list too: LegacyCheckpoint stores validation results and eval params, and updates data docs.

So either way, a separate call to build_data_docs should not be necessary...

**Comment by juliankeppel** [comment]
@spbail Thank you for your reponse.

Okay, I just missed that. I understand what you mean and found this configuration in our `great_expectations.yaml`, too. 

But anyway, I just ran one test with the current version of GE and your operator and no data_docs where generated.

**Comment by talagluck** [comment]
Hi @juliankeppel!

I just tested this, and I'm having trouble reproducing it. When I ran the airflow operator once in a project where I had deleted the data docs folder, I found that the data docs site was generated. The airflow operator doesn't open the data docs site - that will need to be opened manually. One other question - I see the directory path that you mention above is `great_expectations/data_docs`. By default, data docs sites are generated in `great_expectations/uncommitted/data_docs`. Is it possible that is the issue? If you would like the sites to be generated in another location, that will need to be configured in your `great_expectations.yml`.

If that's not it, I'd be happy to touch base to discuss further.

**Comment by juliankeppel** [comment]
Hi @talagluck 

Sorry for that... sure, you're right. I missed the uncommitted folder because I've not expected the docs to be generated there.

Thanks for your support.

So from my side, this PR can be closed!

**Comment by talagluck** [comment]
Thanks @juliankeppel! When you first run `great_expectations init` we put the `data_docs` directory inside of uncommitted in case there is any sensitive data in `data_docs`. If you decide that that is not an issue and would like to move it, you can do so by updating the `base_directory` in your `great_expectations.yml`

 I'll close this for now, but I hope you're able to contribute more soon!

**Pull request closed without merging**
